/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as HelpIndexImport } from './routes/help/index'
import { Route as GeneratingIndexImport } from './routes/generating/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as SettingsPreferencesIndexImport } from './routes/settings/preferences/index'
import { Route as SettingsPlanIndexImport } from './routes/settings/plan/index'
import { Route as RecipesSavedIndexImport } from './routes/recipes/saved/index'
import { Route as RecipesIdIndexImport } from './routes/recipes/$id/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any)

const HelpIndexRoute = HelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRoute,
} as any)

const GeneratingIndexRoute = GeneratingIndexImport.update({
  id: '/generating/',
  path: '/generating/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsPreferencesIndexRoute = SettingsPreferencesIndexImport.update({
  id: '/settings/preferences/',
  path: '/settings/preferences/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsPlanIndexRoute = SettingsPlanIndexImport.update({
  id: '/settings/plan/',
  path: '/settings/plan/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesSavedIndexRoute = RecipesSavedIndexImport.update({
  id: '/recipes/saved/',
  path: '/recipes/saved/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIdIndexRoute = RecipesIdIndexImport.update({
  id: '/recipes/$id/',
  path: '/recipes/$id/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/generating/': {
      id: '/generating/'
      path: '/generating'
      fullPath: '/generating'
      preLoaderRoute: typeof GeneratingIndexImport
      parentRoute: typeof rootRoute
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/saved/': {
      id: '/recipes/saved/'
      path: '/recipes/saved'
      fullPath: '/recipes/saved'
      preLoaderRoute: typeof RecipesSavedIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/plan/': {
      id: '/settings/plan/'
      path: '/settings/plan'
      fullPath: '/settings/plan'
      preLoaderRoute: typeof SettingsPlanIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/preferences/': {
      id: '/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/generating': typeof GeneratingIndexRoute
  '/help': typeof HelpIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/recipes/saved': typeof RecipesSavedIndexRoute
  '/settings/plan': typeof SettingsPlanIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/generating': typeof GeneratingIndexRoute
  '/help': typeof HelpIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/recipes/saved': typeof RecipesSavedIndexRoute
  '/settings/plan': typeof SettingsPlanIndexRoute
  '/settings/preferences': typeof SettingsPreferencesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/generating/': typeof GeneratingIndexRoute
  '/help/': typeof HelpIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/recipes/saved/': typeof RecipesSavedIndexRoute
  '/settings/plan/': typeof SettingsPlanIndexRoute
  '/settings/preferences/': typeof SettingsPreferencesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/generating'
    | '/help'
    | '/recipes'
    | '/recipes/$id'
    | '/recipes/saved'
    | '/settings/plan'
    | '/settings/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/generating'
    | '/help'
    | '/recipes'
    | '/recipes/$id'
    | '/recipes/saved'
    | '/settings/plan'
    | '/settings/preferences'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/generating/'
    | '/help/'
    | '/recipes/'
    | '/recipes/$id/'
    | '/recipes/saved/'
    | '/settings/plan/'
    | '/settings/preferences/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GeneratingIndexRoute: typeof GeneratingIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
  RecipesSavedIndexRoute: typeof RecipesSavedIndexRoute
  SettingsPlanIndexRoute: typeof SettingsPlanIndexRoute
  SettingsPreferencesIndexRoute: typeof SettingsPreferencesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GeneratingIndexRoute: GeneratingIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
  RecipesSavedIndexRoute: RecipesSavedIndexRoute,
  SettingsPlanIndexRoute: SettingsPlanIndexRoute,
  SettingsPreferencesIndexRoute: SettingsPreferencesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/generating/",
        "/help/",
        "/recipes/",
        "/recipes/$id/",
        "/recipes/saved/",
        "/settings/plan/",
        "/settings/preferences/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/generating/": {
      "filePath": "generating/index.tsx"
    },
    "/help/": {
      "filePath": "help/index.tsx"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    },
    "/recipes/$id/": {
      "filePath": "recipes/$id/index.tsx"
    },
    "/recipes/saved/": {
      "filePath": "recipes/saved/index.tsx"
    },
    "/settings/plan/": {
      "filePath": "settings/plan/index.tsx"
    },
    "/settings/preferences/": {
      "filePath": "settings/preferences/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
