/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as RecipesSavedIndexImport } from './routes/recipes/saved/index'
import { Route as RecipesIdIndexImport } from './routes/recipes/$id/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesSavedIndexRoute = RecipesSavedIndexImport.update({
  id: '/recipes/saved/',
  path: '/recipes/saved/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIdIndexRoute = RecipesIdIndexImport.update({
  id: '/recipes/$id/',
  path: '/recipes/$id/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes/saved/': {
      id: '/recipes/saved/'
      path: '/recipes/saved'
      fullPath: '/recipes/saved'
      preLoaderRoute: typeof RecipesSavedIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/recipes/saved': typeof RecipesSavedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
  '/recipes/saved': typeof RecipesSavedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
  '/recipes/saved/': typeof RecipesSavedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/recipes' | '/recipes/$id' | '/recipes/saved'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/recipes' | '/recipes/$id' | '/recipes/saved'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/recipes/'
    | '/recipes/$id/'
    | '/recipes/saved/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
  RecipesSavedIndexRoute: typeof RecipesSavedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
  RecipesSavedIndexRoute: RecipesSavedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/recipes/",
        "/recipes/$id/",
        "/recipes/saved/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx"
    },
    "/recipes/$id/": {
      "filePath": "recipes/$id/index.tsx"
    },
    "/recipes/saved/": {
      "filePath": "recipes/saved/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
